export const ADD_TODO = 'TODO_ITEM/ADD';
export const EDIT_TODO = 'TODO_ITEM/EDIT';
export const DELETE_TODO = 'TODO_ITEM/DELETE';
export const TOGGLE_CHECK_TODO = 'TODO_ITEM/TOGGLE_CHECK';
export const FETCH_TODO_ITEMS = 'TODO_LIST/FETCH_TODOS';
